# Generated by Django 5.2.8 on 2025-11-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0002_studentprofile_domain_studentprofile_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('internship', 'Internship'), ('pfe', 'PFE'), ('job', 'First Job')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='offers/pdfs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='profiles.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='catalog.domain')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'unique_together': {('offer', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='domain',
            field=models.ManyToManyField(blank=True, through='offers.RequiredDomain', to='catalog.domain'),
        ),
        migrations.CreateModel(
            name='RequiredInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='catalog.institution')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'unique_together': {('offer', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='institutions',
            field=models.ManyToManyField(blank=True, through='offers.RequiredInstitution', to='catalog.institution'),
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='catalog.skill')),
            ],
            options={
                'unique_together': {('offer', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='required_skills',
            field=models.ManyToManyField(blank=True, through='offers.RequiredSkill', to='catalog.skill'),
        ),
        migrations.CreateModel(
            name='RequiredSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='catalog.specialty')),
            ],
            options={
                'unique_together': {('offer', 'specialty')},
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='specialty',
            field=models.ManyToManyField(blank=True, through='offers.RequiredSpecialty', to='catalog.specialty'),
        ),
    ]
